### ISSUE TITLE
Review dev-rob

### ISSUE THREAD

**Issue by CmdrRob** [j3ro3n/madlibs#1]
The project so far:

- [x] Functional test
- [x] Do code review
- [x] Update documentation / wireframes
- [x] Add all requirements ready for testing to this ticket.

**Comment by j3ro3n** [comment]
Functie test
Gui loopt goed. Geen afwijkingen in layout. Alle knoppen werken en input velden kunnen worden gevuld tot maximum aantal. Timer werk. Snackbar werkt met juiste meldingen. Quit button werkt. Sessieid wordt getoond en getoond bij eigen invoer.

**Comment by j3ro3n** [comment]
Code review
Het enige is dat in de html files mijn IDE aangeeft dat sommige closing tags tot niets leiden. Dit heeft geen invloed op de GUI.
Code ziet er netjes en gestructureerd uit. 
Iets om te zeiken is om meer comments bij de functionaliteiten te zetten, zodat gelezen kan worden wat de functie doet.

**Comment by j3ro3n** [comment]
Documentation Wireframes
Notitie aangevuld in de wireframe voor het combineren van intro en login. Tevens het aantal categorieën van 10 naar 4 aangegeven.

**Comment by j3ro3n** [comment]
Add requirements for testing.
Project Frondend-testusecase gemaakt met daarin 7 categorieën met de diverse tests. Test cases die nog niet gedaan kunnen worden gelabeld. Toegewezen aan Sven en met hem contact gehad dat het zo het makkelijkst is
