### ISSUE TITLE
Game State API call

### ISSUE THREAD

**Issue by CmdrRob** [j3ro3n/madlibs#26]
### API url endpoint
'/gamestate'

### requestJson payload
```
{
    nickname: string,
    playerid: string,
    sessieid: string,
    sessieTimer: number
}
```

### Expected server action
The server needs to save the session. If 'sessieid' is empty, generate 5 random characters (alphanumerical) and save the session under that. As part of this session, save the 'sessieTimer' as the timer value for this session.

If 'sessieid' is set and the session is non-existent, create a session on that address like above.

If 'sessieid' is set and the session exists, try to add the player to that session. If the session already has six players, send an error json back. If the session does not already have six players, add the player to the session and return the gamestate json.

### responseJson payload (gamestate)
```
{
    sessieid: string,
    player_1_name: string,
    player_1_score: number,
    player_1_id: string,
    player_2_name: string,
    player_2_score: number,
    player_2_id: string,
    player_3_name: string,
    player_3_score: number,
    player_3_id: string,
    player_4_name: string,
    player_4_score: number,
    player_4_id: string,
    player_5_name: string,
    player_5_score: number,
    player_5_id: string,
    player_6_name: string,
    player_6_score: number,
    player_6_id: string,
    sessieTimer: number
}
```

### responseJson payload (error)
```
{
    error: "session-full-error"
}
```

**Comment by seeringfate** [comment]
If we can ad player ID's then it's a go; so then it will be:
**requestJson payload**
```
{
    nickname: string,
    playerid: string,
    sessieid: string,
    sessieTimer: number
}
```
Player ID can be left empty up creating or joining a session, when asking for the gamestate as an update, add the player id to the request. This will prevent duplicate names from being a problem.
**responseJson payload**
```
{
    sessieid: string,
    player_1_name: string,
    player_1_score: number,
    player_1_id: string,
    player_2_name: string,
    player_2_score: number,
    player_2_id: string,
    player_3_name: string,
    player_3_score: number,
    player_3_id: string,
    player_4_name: string,
    player_4_score: number,
    player_4_id: string,
    player_5_name: string,
    player_5_score: number,
    player_5_id: string,
    player_6_name: string,
    player_6_score: number,
    player_6_id: string,
    sessieTimer: number
}
```
Error looks good

**Comment by CmdrRob** [comment]
Adapted as discussed on phone: Now passing player id back and forth.
