### ISSUE TITLE
Mad Lib API call

### ISSUE THREAD

**Issue by CmdrRob** [j3ro3n/madlibs#27]
### API url endpoint 
'/madlib'

### requestJson payload 
```
{
    sessieid: string,
    request: "mad lib"
}
```

### Expected server action
The server should keep a state for the session. The state should be 'Initial', 'Game', or 'Vote'. Based on the state, the server should generate a response.

~~When a session is first created, State is initialized as **'Initial'**. When this request comes in for the Initial state, the state is set to 'Game'. A mad lib is generated, saved to the session, and returned as a JSON to the requesting client.~~

~~While in the **'game'** state, when this request comes in from a client, return the mad lib that is stored in the session for the ID sent.~~

~~When the client first submits a mad lib, the game moves to **'vote'** state. While in this state, the server should reply with an error JSON.~~

~~After all the players have voted, the state should go back to 'Initial'.~~

States:

* Initial - The starting point of the application. The trigger for this state is when a session is first created, but no mad libs were requested yet. **Response**: A fresh mad lib (that is then saved to the session).
* Game - The game is in progress. The trigger for this state is when a player in the session first requests a mad lib (either from the initial state or from the voting state). **Response**: The mad lib that has been saved for the session.
* Vote - The game is in the voting state. The trigger for this state is when a player first submits a completed mad lib. **Response**: An error message saying voting is in progress.

### responseJson payload (mad lib) (example)
```
{
	"madlib": "Some funny Sentence.",
	"categories": [
		{
			"type": "Creature",
			"words": [
				{
					"id": 1,
					"word_1": "Fish",
					"word_2": "Godzilla",
					"word_3": "Trump",
					"word_4": "Towely"
				},
				{
					"id": 2,
					"word_1": "Fish",
					"word_2": "Godzilla",
					"word_3": "Trump",
					"word_4": "Towely"
				},
				{
					"id": 3,
					"word_1": "Fish",
					"word_2": "Godzilla",
					"word_3": "Trump",
					"word_4": "Towely"
				}
			]
		},
		{
			"type": "Event",
			"words": [
				{
					"id": 1,
					"word_1": "Fish",
					"word_2": "Godzilla",
					"word_3": "Trump",
					"word_4": "Towely"
				},
				{
					"id": 2,
					"word_1": "Fish",
					"word_2": "Godzilla",
					"word_3": "Trump",
					"word_4": "Towely"
				}
			]
		},
		{
			"type": "Object",
			"words": [
				{
					"id": 1,
					"word_1": "Fish",
					"word_2": "Godzilla",
					"word_3": "Trump",
					"word_4": "Towely"
				}
			]
		}
	]
}
```

\* In the madlib string, all categories should be capitalized and prefixed with a dollar sign ($) to signify that this is where a word needs to be replaced. Note that these entries do not need to be numbered and are exclusively the category.
i.e. "$PERSON punched $PERSON in the face after they insulted their $VERB".

### responseJson payload (error)
```
{
    error: "vote-in-progress-error"
}
```

**Comment by seeringfate** [comment]
Is it a problem if I always send all possible categories, but the ones that are not used are empty ?
Also, do you want the id to be different bassed of the category or do they all need to have a unique id?
EG:
{
    madlib: string*,
    category: [
        {
            id: **1**,
            category_1: string,
            category_2: string,
            category_3: string,
            category_4: string
        },
        {
            id: **2**,
            category_1: string,
            category_2: string,
            category_3: string,
            category_4: string
        },
    ],

    category2: [
        {
            id: **1,**
            category_1: string,
            category_2: string,
            category_3: string,
            category_4: string
        },
        {
            id: **2**,
            category_1: string,
            category_2: string,
            category_3: string,
            category_4: string
        },
    ],
}
or 
{
    madlib: string*,
    category: [
        {
            id: **1**,
            category_1: string,
            category_2: string,
            category_3: string,
            category_4: string
        },
        {
            id: **2**,
            category_1: string,
            category_2: string,
            category_3: string,
            category_4: string
        },
    ],

    category2: [
        {
            id: **3**,
            category_1: string,
            category_2: string,
            category_3: string,
            category_4: string
        },
        {
            id: **4**,
            category_1: string,
            category_2: string,
            category_3: string,
            category_4: string
        },
    ],
}

Also the gamestate sound good, but It's unclear for me right now at what specific time I need to progress it.

**Comment by CmdrRob** [comment]
Gamestate discussed on phone, recap on triggers (also added to OP):

States: 
* Initial - The starting point of the application. The trigger for this state is when a session is first created, but no mad libs were requested yet.
* Game - The game is in progress. The trigger for this state is when a player in the session first requests a mad lib (either from the initial state or from the voting state).
* Vote - The game is in the voting state. The trigger for this state is when a player first submits a completed mad lib.

Also, response JSON was discussed on phone and was concluded to need a different system. @seeringfate can you suggest a new output format that will make it possible for you to only submit the categories that are needed for a mad lib and that will allow you to dynamically decide which categories live in the backend?

**Comment by seeringfate** [comment]
Accepted format:
```
{
	"madlib": "Some funny Sentence.",
	"categories": [
		{
			"type": "Creature",
			"creature": [
				{
					"id": 1,
					"creature_1": "Fish",
					"creature_2": "Godzilla",
					"creature_3": "Trump",
					"creature_4": "Towely"
				},
				{
					"id": 2,
					"creature_1": "Fish",
					"creature_2": "Godzilla",
					"creature_3": "Trump",
					"creature_4": "Towely"
				},
				{
					"id": 3,
					"creature_1": "Fish",
					"creature_2": "Godzilla",
					"creature_3": "Trump",
					"creature_4": "Towely"
				}
			]
		},
		{
			"type": "Event",
			"event": [
				{
					"id": 1,
					"event_1": "Fish",
					"event_2": "Godzilla",
					"event_3": "Trump",
					"event_4": "Towely"
				},
				{
					"id": 2,
					"event_1": "Fish",
					"event_2": "Godzilla",
					"event_3": "Trump",
					"event_4": "Towely"
				}
			]
		},
		{
			"type": "Object",
			"object": [
				{
					"id": 1,
					"object_1": "Fish",
					"object_2": "Godzilla",
					"object_3": "Trump",
					"object_4": "Towely"
				}
			]
		}
	]
}
```

**Comment by seeringfate** [comment]
Extra state: "Final".
Madlib can only be requested in the "Initial","Game" en "Final"
