### ISSUE TITLE
Submit Mad Lib API call

### ISSUE THREAD

**Issue by CmdrRob** [j3ro3n/madlibs#30]
### API url endpoint 
'/submit'

### requestJson payload 
```
{
    sessieid: string,
    nickname: string,
    playerid: string,
    madlib: string,
    voteable: boolean
}
```

### Expected server action
When receiving this JSON, the server needs to keep a running tally of the players in the session. For each player in a session, the server temporarily saves the created mad lib.

If not all players have sent in their mad libs yet, the server will send back an error JSON.

If all players have sent in their mad libs (ie. there is a request for each of the players in the session), the server sends back a response JSON with all the players' mad libs in them.

### responseJson payload (mad libs)
```
{
    sessieid: string,
    player1_name: string,
    player1_madlib: string,
    player1_id: string, 
    player1_voteable: string,
    player2_name: string,
    player2_madlib: string,
    player2_id: string,
    player2_voteable: string,
    player3_name: string,
    player3_madlib: string,
    player3_id: string,
    player3_voteable: string,
    player4_name: string,
    player4_madlib: string,
    player4_id: string,
    player4_voteable: string,
    player5_name: string,
    player5_madlib: string,
    player5_id: string,
    player5_voteable: string,
    player6_name: string,
    player6_madlib: string,
    player6_id: string,
    player6_voteable: string
}
```
\* Note: The '_voteable' properties are string representations of a boolean, but importantly, are `""` by default.

### responseJson payload (error)
```
{
  error: "awaiting-submissions-error"
}
```

**Comment by seeringfate** [comment]
Same here as gamestate, add the ID's, from here on these will be provided from the server side.
{
  sessied: string,
  nickname: string,
  playerid: string,
  madlib: string
}

{
  sessieid: string,
  player1_name: string,
  player1_madlib: string,
  player1_id: string,
  player2_name: string,
  player2_madlib: string,
  player2_id: string,
  player3_name: string,
  player3_madlib: string,
  player3_id: string,
  player4_name: string,
  player4_madlib: string,
  player4_id: string,
  player5_name: string,
  player5_madlib: string,
  player5_id: string,
  player6_name: string,
  player6_madlib: string
  player6_id: string,
}

**Comment by CmdrRob** [comment]
OP updated as discussed on phone.

**Comment by CmdrRob** [comment]
OP updated a little more. I pass along a boolean that lets the backend know if the player was disqualified. If the player was disqualified, their button will be disabled on the voting screen. Just so you know.

In essence, more data to collect from each player and to pass back.
